language: python
services:
    - docker
python:
    - "2.7"
install:
    - make deps
script:
    - make lint
    - make test
    - make test_xunit 
    - make docker_build
deploy:
  provider: heroku
  app: ancient-cove-74343
  api_key: ${HEROKU_API_KEY}
