language: python
services:
- docker
python:
- '2.7'
install:
- make deps
script:
- make lint
- make test
- make docker_build
- make docker_push
env:
  global:
    secure:
  deploy:
  provider: heroku
  app: enigmatic-wave-49275
api_key: ${HEROKU_API_KEY}
